from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.validators import RegexValidator
from django.utils import timezone
from departments.models import Department
import uuid
from django.core.exceptions import ValidationError
from PIL import Image, UnidentifiedImageError


class CustomUserQuerySet(models.QuerySet):
    def included_in_metrics(self):
        """Return users that should be counted in dashboards/metrics."""
        return self.filter(exclude_from_metrics=False)


class CustomUserManager(UserManager.from_queryset(CustomUserQuerySet)):
    pass


class CustomUser(AbstractUser):
    """
    Custom User model with extended fields for employee management
    Based on requirements document specifications
    """
    
    # Employment Information
    employee_id = models.CharField(
        max_length=50,
        unique=True,
        blank=True,
        editable=False,
        help_text="Unique employee identifier generated by the system"
    )
    
    national_id = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Government ID number (encrypted in database)"
    )
    
    # Contact Information
    phone_primary = models.CharField(
        max_length=20,
        validators=[
            RegexValidator(
                regex=r'^\+?1?\d{9,15}$',
                message="Phone number must be entered in international format."
            )
        ],
        help_text="Primary phone number (international format)"
    )
    
    phone_secondary = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^\+?1?\d{9,15}$',
                message="Phone number must be entered in international format."
            )
        ],
        help_text="Secondary phone number (optional)"
    )
    
    personal_email = models.EmailField(
        blank=True,
        null=True,
        help_text="Personal email address (different from work email)"
    )
    
    # Position & Employment
    EMPLOYMENT_TYPE_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Contract', 'Contract'),
        ('Intern', 'Intern'),
        ('Consultant', 'Consultant'),
    ]
    
    employment_type = models.CharField(
        max_length=20,
        choices=EMPLOYMENT_TYPE_CHOICES,
        default='Full-time'
    )
    
    EMPLOYMENT_STATUS_CHOICES = [
        ('Active', 'Active'),
        ('On Leave', 'On Leave'),
        ('Suspended', 'Suspended'),
        ('Terminated', 'Terminated'),
    ]
    
    employment_status = models.CharField(
        max_length=20,
        choices=EMPLOYMENT_STATUS_CHOICES,
        default='Active'
    )
    
    position = models.CharField(
        max_length=200,
        help_text="Job title or position"
    )
    
    job_title = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text="Alternative field for job title"
    )
    
    join_date = models.DateField(
        default=timezone.now,
        help_text="Employee start date"
    )
    
    end_date = models.DateField(
        blank=True,
        null=True,
        help_text="For terminated/resigned employees"
    )
    
    probation_end_date = models.DateField(
        blank=True,
        null=True,
        help_text="End of probation period"
    )
    
    # Department & Hierarchy
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='department_members'
    )
    
    sub_department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='sub_department_members'
    )
    
    reports_to = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='direct_reports'
    )
    
    EMPLOYEE_LEVEL_CHOICES = [
        ('Entry', 'Entry'),
        ('Junior', 'Junior'),
        ('Mid', 'Mid'),
        ('Senior', 'Senior'),
        ('Lead', 'Lead'),
        ('Manager', 'Manager'),
        ('Director', 'Director'),
        ('Executive', 'Executive'),
    ]
    
    employee_level = models.CharField(
        max_length=20,
        choices=EMPLOYEE_LEVEL_CHOICES,
        default='Entry'
    )
    
    # IT Administrator Governance (RHG 4.3)
    is_it_administrator = models.BooleanField(
        default=False,
        help_text="User is authorized as IT Administrator (RHG 4.3 scope)",
    )

    it_admin_certification_date = models.DateField(
        blank=True,
        null=True,
        help_text="Date the user was certified/authorized as IT Administrator",
    )

    it_admin_certified_by = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="it_admin_certifications",
        blank=True,
        null=True,
        help_text="Who approved the user as IT Administrator",
    )

    # Location & Contact
    office_location = models.CharField(
        max_length=200,
        default='Headquarters',
        help_text="Office location (e.g., Headquarters, Branch A, Remote)"
    )
    
    office_room = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Room or desk number"
    )
    
    work_address = models.TextField(
        blank=True,
        null=True,
        help_text="Full work address"
    )
    
    city = models.CharField(max_length=100, blank=True, null=True)
    state_province = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    
    # Additional Information
    def _validate_profile_photo(file_field):
        if not file_field:
            return
        max_mb = 2
        if getattr(file_field, 'size', 0) > max_mb * 1024 * 1024:
            raise ValidationError(f"Profile photo must be <= {max_mb}MB.")
        # Validate image integrity and format using Pillow
        try:
            # Ensure stream at start
            if hasattr(file_field, 'seek'):
                file_field.seek(0)
            img = Image.open(file_field)
            img.verify()  # verify file is not corrupted
            fmt = getattr(img, 'format', None)
            if fmt not in ['JPEG', 'PNG']:
                raise ValidationError("Profile photo must be a JPG or PNG image.")
        except (UnidentifiedImageError, OSError):
            raise ValidationError("Invalid image file. Please upload a valid JPG or PNG image.")
        finally:
            try:
                if hasattr(file_field, 'seek'):
                    file_field.seek(0)
            except Exception:
                pass

    profile_photo = models.ImageField(
        upload_to='profiles/',
        blank=True,
        null=True,
        help_text="Profile photo (max 2MB, JPG/PNG formats)",
        validators=[_validate_profile_photo]
    )
    
    emergency_contact_name = models.CharField(
        max_length=200,
        blank=True,
        null=True
    )
    
    emergency_contact_phone = models.CharField(
        max_length=20,
        blank=True,
        null=True
    )
    
    emergency_contact_relation = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    
    date_of_birth = models.DateField(
        blank=True,
        null=True,
        help_text="For birthday reminders"
    )
    
    description = models.TextField(
        blank=True,
        null=True,
        help_text="User description (visible to users)"
    )
    
    notes = models.TextField(
        blank=True,
        null=True,
        help_text="Admin notes about the user (not visible to regular users)"
    )

    flag_for_follow_up = models.BooleanField(
        default=False,
        help_text="Mark when this user needs a manual follow-up"
    )
    exclude_from_metrics = models.BooleanField(
        default=False,
        help_text="Exclude this account from total user counts and dashboards"
    )
    
    # AD Integration Fields (Future)
    ad_username = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text="Active Directory username"
    )
    
    ad_synced = models.BooleanField(
        default=False,
        help_text="True when synced from Active Directory"
    )
    
    last_ad_sync = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Timestamp of last AD sync"
    )
    
    ad_distinguished_name = models.CharField(
        max_length=500,
        blank=True,
        null=True,
        help_text="Full AD DN path"
    )
    
    # Metadata (Automatic)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='users_created'
    )
    updated_by = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='users_updated'
    )
    
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['first_name', 'last_name']
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.employee_id})"
    
    @property
    def full_name(self):
        """Return the user's full name"""
        return f"{self.first_name} {self.last_name}"
    
    @property
    def is_active_employee(self):
        """Check if user is an active employee"""
        return self.employment_status == 'Active' and self.is_active

    @property
    def is_it_admin(self):
        """
        Convenience alias used in templates/reports.
        Indicates whether the user is marked as an IT Administrator.
        """
        return bool(self.is_it_administrator)
    
    def get_department_name(self):
        """Return department name or None"""
        return self.department.name if self.department else None
    
    def get_manager_name(self):
        """Return manager's name or None"""
        return self.reports_to.full_name if self.reports_to else None
    
    def get_active_access_count(self):
        """Return count of active system access"""
        from access_management.models import UserSystemAccess
        return UserSystemAccess.objects.filter(
            user=self,
            access_status='Active'
        ).count()
    
    def save(self, *args, **kwargs):
        """Override save to handle validation and auto-fields"""
        # Set position from job_title if position is empty
        if not self.position and self.job_title:
            self.position = self.job_title

        # Auto-generate employee_id on first save
        if not self.employee_id:
            self.employee_id = self._generate_employee_id()
        
        super().save(*args, **kwargs)

    def _generate_employee_id(self) -> str:
        """
        Generate a unique employee ID with pattern: YYYY-##### (zero-padded).
        Ensures uniqueness by checking existing IDs and incrementing.
        """
        year = timezone.now().year
        prefix = f"{year}-"
        # Find the max sequence for current year
        existing_ids = (
            CustomUser.objects.filter(employee_id__startswith=prefix)
            .values_list('employee_id', flat=True)
        )
        max_seq = 0
        for eid in existing_ids:
            try:
                seq = int(str(eid).split("-", 1)[1])
                if seq > max_seq:
                    max_seq = seq
            except (ValueError, IndexError):
                continue
        next_seq = max_seq + 1
        candidate = f"{prefix}{next_seq:05d}"
        # Guarantee uniqueness in rare race conditions
        while CustomUser.objects.filter(employee_id=candidate).exists():
            next_seq += 1
            candidate = f"{prefix}{next_seq:05d}"
        return candidate

    objects = CustomUserManager()


class UserDeactivationAudit(models.Model):
    user = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='deactivation_audits',
    )
    user_username = models.CharField(max_length=150)
    user_full_name = models.CharField(max_length=255, blank=True)
    user_employee_id = models.CharField(max_length=50, blank=True)
    admin = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='deactivation_actions',
    )
    deactivated_at = models.DateTimeField(auto_now_add=True)
    system_confirmed = models.BooleanField(default=False)
    hardware_confirmed = models.BooleanField(default=False)
    hardware_status_action = models.CharField(max_length=20, default='no_change')
    system_assignments = models.JSONField(default=list, blank=True)
    hardware_assignments = models.JSONField(default=list, blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['-deactivated_at']
        verbose_name = 'User Deactivation Audit'
        verbose_name_plural = 'User Deactivation Audits'

    def __str__(self):
        return f"{self.user_username} deactivated on {self.deactivated_at:%Y-%m-%d %H:%M}"


class UserArchive(models.Model):
    source_user_id = models.IntegerField()
    username = models.CharField(max_length=150)
    full_name = models.CharField(max_length=255, blank=True)
    employee_id = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=254, blank=True)
    department_name = models.CharField(max_length=200, blank=True)
    archived_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='user_archives_created',
    )
    archived_at = models.DateTimeField(auto_now_add=True)
    payload = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ['-archived_at']
        verbose_name = 'Archived User'
        verbose_name_plural = 'Archived Users'

    def __str__(self):
        return f"Archived user {self.username} ({self.employee_id}) at {self.archived_at:%Y-%m-%d %H:%M}"


class LDAPConfiguration(models.Model):
    """
    LDAP/Active Directory configuration settings
    Follows Snipe-IT style comprehensive LDAP configuration
    """
    # Server Settings
    ldap_enabled = models.BooleanField(
        default=False,
        help_text="Enable LDAP authentication"
    )
    
    is_active_directory = models.BooleanField(
        default=True,
        help_text="This is an Active Directory server"
    )
    
    cache_passwords = models.BooleanField(
        default=True,
        help_text="Cache LDAP passwords as local hashed passwords. Uncheck if you don't want to keep LDAP passwords cached."
    )
    
    ad_domain = models.CharField(
        max_length=255,
        blank=True,
        help_text="Active Directory domain (sometimes the same as email domain)"
    )
    
    # TLS/SSL Settings
    ldap_client_tls_key = models.TextField(
        blank=True,
        help_text="LDAP Client-Side TLS Key (usually for Google Workspace Secure LDAP)"
    )
    
    ldap_client_tls_cert = models.TextField(
        blank=True,
        help_text="LDAP Client-Side TLS Certificate (usually for Google Workspace Secure LDAP)"
    )
    
    ldap_server = models.CharField(
        max_length=500,
        default='ldap://ldap.example.com:389',
        help_text="LDAP Server URL (ldap:// for unencrypted or ldaps:// for TLS/SSL)"
    )
    
    use_tls = models.BooleanField(
        default=False,
        help_text="Use STARTTLS for LDAP connection"
    )
    
    allow_invalid_ssl = models.BooleanField(
        default=False,
        help_text="Allow invalid SSL certificates (for self-signed certificates)"
    )
    
    # Bind Settings
    bind_username = models.CharField(
        max_length=500,
        blank=True,
        help_text="LDAP Bind Username (full DN or UPN format)"
    )
    
    bind_password = models.CharField(
        max_length=500,
        blank=True,
        help_text="LDAP Bind Password"
    )
    
    base_dn = models.CharField(
        max_length=500,
        blank=True,
        help_text="Base Bind DN (e.g., DC=example,DC=com)"
    )
    
    # Search and Authentication
    ldap_filter = models.CharField(
        max_length=500,
        default='(&(objectClass=user)(objectCategory=person))',
        blank=True,
        help_text="LDAP Filter for user search"
    )
    
    ldap_auth_query = models.CharField(
        max_length=500,
        blank=True,
        help_text="LDAP Authentication query"
    )
    
    default_permission_group = models.ForeignKey(
        'auth.Group',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Default permission group for new LDAP users"
    )
    
    # Field Mapping
    ldap_username_field = models.CharField(
        max_length=100,
        default='samaccountname',
        help_text="LDAP Username Field (use lowercase for AD: samaccountname)"
    )
    
    ldap_lastname_field = models.CharField(
        max_length=100,
        default='sn',
        help_text="LDAP Last Name Field"
    )
    
    ldap_firstname_field = models.CharField(
        max_length=100,
        default='givenname',
        help_text="LDAP First Name Field (use lowercase: givenname)"
    )
    
    ldap_displayname_field = models.CharField(
        max_length=100,
        default='displayname',
        blank=True,
        help_text="LDAP Display Name Field (use lowercase: displayname)"
    )
    
    ldap_employeenumber_field = models.CharField(
        max_length=100,
        default='employeenumber',
        blank=True,
        help_text="LDAP Employee Number Field"
    )
    
    ldap_department_field = models.CharField(
        max_length=100,
        default='department',
        blank=True,
        help_text="LDAP Department Field"
    )
    
    ldap_manager_field = models.CharField(
        max_length=100,
        default='manager',
        blank=True,
        help_text="LDAP Manager Field (DN of manager)"
    )
    
    ldap_email_field = models.CharField(
        max_length=100,
        default='mail',
        help_text="LDAP Email Field"
    )
    
    ldap_phone_field = models.CharField(
        max_length=100,
        default='telephonenumber',
        blank=True,
        help_text="LDAP Phone Number Field"
    )
    
    ldap_mobile_field = models.CharField(
        max_length=100,
        default='mobile',
        blank=True,
        help_text="LDAP Mobile Field"
    )
    
    ldap_jobtitle_field = models.CharField(
        max_length=100,
        default='title',
        blank=True,
        help_text="LDAP Job Title Field"
    )
    
    ldap_address_field = models.CharField(
        max_length=100,
        default='streetaddress',
        blank=True,
        help_text="LDAP Address Field"
    )
    
    ldap_city_field = models.CharField(
        max_length=100,
        default='l',
        blank=True,
        help_text="LDAP City Field"
    )
    
    ldap_state_field = models.CharField(
        max_length=100,
        default='st',
        blank=True,
        help_text="LDAP State/Province Field"
    )
    
    ldap_postalcode_field = models.CharField(
        max_length=100,
        default='postalcode',
        blank=True,
        help_text="LDAP Postal Code Field"
    )
    
    ldap_country_field = models.CharField(
        max_length=100,
        default='co',
        blank=True,
        help_text="LDAP Country Field"
    )
    
    ldap_location_field = models.CharField(
        max_length=100,
        default='',
        blank=True,
        help_text="LDAP Location Field (if not using OU in Base Bind DN)"
    )
    
    ldap_active_flag = models.CharField(
        max_length=100,
        default='useraccountcontrol',
        blank=True,
        help_text="LDAP Active Flag field (userAccountControl for AD)"
    )
    
    ldap_invert_active_flag = models.BooleanField(
        default=False,
        help_text="Invert the active flag logic (enabled when value is 0 or false)"
    )
    
    # Miscellaneous
    custom_password_reset_url = models.URLField(
        max_length=500,
        blank=True,
        help_text="Custom password reset URL for LDAP users"
    )
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        CustomUser,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ldap_configs_updated'
    )
    
    class Meta:
        verbose_name = 'LDAP Configuration'
        verbose_name_plural = 'LDAP Configurations'
    
    def __str__(self):
        return f"LDAP Config - {'Enabled' if self.ldap_enabled else 'Disabled'} - {self.ldap_server}"
    
    @classmethod
    def get_active_config(cls):
        """Get the active LDAP configuration"""
        return cls.objects.filter(ldap_enabled=True).first()