# Generated by Django 5.2.8 on 2025-11-10 11:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Requested', 'Access Requested'), ('Approved', 'Access Approved'), ('Rejected', 'Access Rejected'), ('Activated', 'Access Activated'), ('Suspended', 'Access Suspended'), ('Revoked', 'Access Revoked'), ('Expired', 'Access Expired'), ('Reviewed', 'Access Reviewed'), ('Modified', 'Access Modified'), ('Password Reset', 'Password Reset'), ('Login', 'User Login'), ('Logout', 'User Logout'), ('Failed Login', 'Failed Login Attempt'), ('Access Denied', 'Access Denied')], help_text='Type of access action', max_length=30)),
                ('action_description', models.TextField(blank=True, help_text='Detailed description of the action', null=True)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the access event occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which access was attempted', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the browser/client', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the access attempt was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if access failed', null=True)),
                ('access_level', models.CharField(blank=True, help_text='Access level at the time of the event', max_length=50, null=True)),
                ('session_duration', models.IntegerField(blank=True, help_text='Session duration in minutes (for login events)', null=True)),
            ],
            options={
                'verbose_name': 'Access History',
                'verbose_name_plural': 'Access History',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSystemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('Full Access', 'Full Access'), ('Read Only', 'Read Only'), ('Read/Write', 'Read/Write'), ('Admin', 'Administrator'), ('Super Admin', 'Super Administrator'), ('Limited', 'Limited Access'), ('Custom', 'Custom Access'), ('Temporary', 'Temporary Access')], default='Read Only', help_text='Type of access being granted', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Active', 'Active'), ('Suspended', 'Suspended'), ('Revoked', 'Revoked'), ('Expired', 'Expired'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the access request', max_length=20)),
                ('request_type', models.CharField(choices=[('New Access', 'New Access Request'), ('Access Renewal', 'Access Renewal'), ('Access Upgrade', 'Access Upgrade'), ('Access Downgrade', 'Access Downgrade'), ('Emergency Access', 'Emergency Access')], default='New Access', help_text='Type of access request', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', help_text='Request priority level', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date when access was requested')),
                ('requested_access_duration', models.IntegerField(blank=True, help_text='Requested access duration in days (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('business_justification', models.TextField(help_text='Business justification for access request')),
                ('technical_requirements', models.TextField(blank=True, help_text='Technical requirements or specifications', null=True)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date when access was approved', null=True)),
                ('approval_comments', models.TextField(blank=True, help_text='Comments from approver', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('granted_access_level', models.CharField(blank=True, help_text='Specific access level or role granted', max_length=100, null=True)),
                ('access_username', models.CharField(blank=True, help_text='Username or account name in the system', max_length=100, null=True)),
                ('temporary_password', models.CharField(blank=True, help_text='Temporary password (encrypted)', max_length=100, null=True)),
                ('access_url', models.URLField(blank=True, help_text='Direct URL for system access', null=True)),
                ('access_start_date', models.DateTimeField(blank=True, help_text='When access becomes active (NULL for immediate)', null=True)),
                ('access_end_date', models.DateTimeField(blank=True, help_text='When access expires (NULL for no expiration)', null=True)),
                ('last_review_date', models.DateTimeField(blank=True, help_text='Last access review date', null=True)),
                ('next_review_date', models.DateTimeField(blank=True, help_text='Next scheduled review date', null=True)),
                ('review_frequency_days', models.IntegerField(blank=True, help_text='Review frequency in days', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('security_clearance_required', models.CharField(blank=True, help_text='Security clearance level required', max_length=50, null=True)),
                ('data_access_level', models.CharField(blank=True, help_text='Data classification level accessed', max_length=50, null=True)),
                ('compliance_requirements', models.TextField(blank=True, help_text='Compliance requirements met', null=True)),
                ('risk_assessment_score', models.IntegerField(blank=True, help_text='Risk assessment score (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notify_user_on_access', models.BooleanField(default=True, help_text='Send notification to user when access is granted')),
                ('notify_manager_on_access', models.BooleanField(default=True, help_text="Send notification to user's manager when access is granted")),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for access', null=True)),
                ('attachments', models.FileField(blank=True, help_text='Supporting documents or screenshots', null=True, upload_to='access_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User System Access',
                'verbose_name_plural': 'User System Accesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
