# Generated by Django 5.2.8 on 2025-11-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_management', '0001_initial'),
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesshistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_history_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='system',
            field=models.ForeignKey(help_text='System involved in the access event', on_delete=django.db.models.deletion.CASCADE, related_name='access_history', to='systems.system'),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='user',
            field=models.ForeignKey(help_text='User involved in the access event', on_delete=django.db.models.deletion.CASCADE, related_name='access_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_system_accesses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who made the request (for requests made by managers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='system',
            field=models.ForeignKey(help_text='System being accessed', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='systems.system'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_system_accesses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='user',
            field=models.ForeignKey(help_text='User requesting/receiving access', on_delete=django.db.models.deletion.CASCADE, related_name='system_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='user_system_access',
            field=models.ForeignKey(blank=True, help_text='Related access record (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='access_management.usersystemaccess'),
        ),
        migrations.AlterUniqueTogether(
            name='usersystemaccess',
            unique_together={('user', 'system')},
        ),
    ]
