# Generated by Django 5.2.8 on 2025-11-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemaccess',
            name='generic_account_remediated',
            field=models.BooleanField(default=False, help_text='Whether generic account has been replaced with unique account in external system'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='is_generic_account',
            field=models.BooleanField(default=False, help_text='Flag if this account in the external system is generic (admin, guest, etc.)'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='remediated_by',
            field=models.ForeignKey(blank=True, help_text='User who documented the remediation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_account_remediations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='remediation_date',
            field=models.DateTimeField(blank=True, help_text='Date when generic account was remediated in external system', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='remediation_notes',
            field=models.TextField(blank=True, help_text='Notes on how the generic account was remediated', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='system_username',
            field=models.CharField(blank=True, help_text="Actual username in the external system (e.g., 'john.doe' in AD, 'jdoe' in Opera Cloud)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersystemaccess',
            name='access_username',
            field=models.CharField(blank=True, help_text='Username or account name in the system (deprecated - use system_username)', max_length=100, null=True),
        ),
    ]
