# Generated by Django 5.2.8 on 2025-11-18 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0003_usersystemaccess_generic_account_remediated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemaccess',
            name='username_verification_artifact',
            field=models.FileField(blank=True, help_text='Attachment (screenshot, export, etc.) showing proof of username uniqueness', null=True, upload_to='username_verification_artifacts/'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='username_verification_artifact_url',
            field=models.URLField(blank=True, help_text='Link to external evidence (ticket, document, etc.) for username uniqueness verification', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='username_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified that this external username is unique to the employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='username_verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='username_verified_date',
            field=models.DateTimeField(blank=True, help_text='Date when the username uniqueness was last verified', null=True),
        ),
    ]
