# Generated by Django 5.2.8 on 2025-11-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0004_usersystemaccess_username_verification_artifact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemaccess',
            name='admin_account_username',
            field=models.CharField(blank=True, help_text="Separate admin account username in the external system (e.g., 'John.Doe_Admin')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='admin_password_storage_location',
            field=models.CharField(blank=True, help_text="Where administrator credentials are stored (e.g., 'Financial Controller safe', 'Password vault ref')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='admin_password_stored_by',
            field=models.ForeignKey(blank=True, help_text='Who documented storage of administrator credentials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_password_storage_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='admin_password_stored_date',
            field=models.DateTimeField(blank=True, help_text='When administrator credentials were last placed/verified in the secure storage location', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='has_domain_admin',
            field=models.BooleanField(default=False, help_text='Account has domain admin / equivalent rights (should be False for workstation logins)'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='has_separate_admin_account',
            field=models.BooleanField(default=False, help_text='User has separate admin account (e.g., John.Doe_Admin) in the external system'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='is_admin_access',
            field=models.BooleanField(default=False, help_text='This access grants administrator or equivalent privileges in the external system'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='is_workstation_login',
            field=models.BooleanField(default=False, help_text='Account used for workstation login (should NOT have domain admin in AD)'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='regular_account_username',
            field=models.CharField(blank=True, help_text="Regular non-admin account username in the external system (e.g., 'John.Doe')", max_length=100, null=True),
        ),
    ]
