# Generated by Django 5.2.8 on 2025-11-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0005_usersystemaccess_admin_account_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemaccess',
            name='legitimate_business_need',
            field=models.TextField(blank=True, help_text='Legitimate business need for this access (as agreed with the System Owner)', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='system_owner_approval_date',
            field=models.DateTimeField(blank=True, help_text='When the System Owner approved this access', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='system_owner_approved',
            field=models.BooleanField(default=False, help_text='System Owner has authorized this access in the external system'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='system_owner_approver',
            field=models.ForeignKey(blank=True, help_text='System Owner who authorized this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_owner_access_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
