# Generated by Django 5.2.8 on 2025-11-18 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0006_usersystemaccess_legitimate_business_need_and_more'),
        ('change_management', '0001_initial'),
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionChangeDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_permissions', models.TextField(help_text='Documented permissions before the change')),
                ('new_permissions', models.TextField(help_text='Actual permissions applied in the external system after the change')),
                ('changed_in_external_system_date', models.DateTimeField(help_text='When the change occurred in the external system')),
                ('documented_in_this_system_date', models.DateTimeField(auto_now_add=True, help_text='When this change was logged for audit evidence')),
                ('has_approval', models.BooleanField(default=False, help_text='Was the change approved through change management?')),
                ('notes', models.TextField(blank=True, help_text='Additional context, evidence links, or remediation notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_reference', models.ForeignKey(blank=True, help_text='Reference to the associated change request (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_change_records', to='change_management.accountchangerequest')),
                ('documented_by', models.ForeignKey(help_text='Person who documented this permission change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_documented', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(help_text='Access assignment that was modified in the external system', on_delete=django.db.models.deletion.CASCADE, related_name='permission_change_logs', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Permission Change Documentation',
                'verbose_name_plural': 'Permission Change Documentation',
                'ordering': ['-changed_in_external_system_date', '-created_at'],
                'indexes': [models.Index(fields=['changed_in_external_system_date'], name='access_mana_changed_ab7330_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyAccessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_quarter', models.CharField(help_text="Quarter being reviewed (e.g., '2025-Q1')", max_length=10)),
                ('review_date', models.DateTimeField(help_text='Date and time the quarterly review was conducted')),
                ('approved_permissions', models.TextField(help_text='Approved permissions/roles on record in this system')),
                ('actual_permissions_in_external_system', models.TextField(help_text='Permissions observed in the external system during the review')),
                ('matches_approved', models.BooleanField(default=False, help_text='Do the actual external-system permissions match the approved permissions?')),
                ('discrepancies', models.TextField(blank=True, help_text='Describe any mismatches or required remediation actions', null=True)),
                ('system_owner_confirmed', models.BooleanField(default=False, help_text='System Owner has confirmed the quarterly review outcome')),
                ('system_owner_confirmed_date', models.DateTimeField(blank=True, help_text='Date/time the System Owner confirmed the review', null=True)),
                ('system_owner_notes', models.TextField(blank=True, help_text='Notes or confirmation evidence from the System Owner', null=True)),
                ('review_completed', models.BooleanField(default=False, help_text='Check when review tasks and follow-ups have been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(help_text='IT reviewer who conducted the quarterly review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterly_reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_user', models.ForeignKey(help_text='Employee whose access was reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_access_reviews', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(help_text='External system that was reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_access_reviews', to='systems.system')),
                ('system_owner', models.ForeignKey(blank=True, help_text='System Owner who confirms the review results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterly_reviews_confirmed', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(blank=True, help_text='Link to the access assignment that was reviewed (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterly_reviews', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Quarterly Access Review',
                'verbose_name_plural': 'Quarterly Access Reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['review_quarter'], name='access_mana_review__c03a1f_idx'), models.Index(fields=['system'], name='access_mana_system__f2fc8c_idx'), models.Index(fields=['reviewed_user'], name='access_mana_reviewe_73e9cb_idx')],
            },
        ),
    ]
