# Generated by Django 5.2.8 on 2025-11-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0007_permissionchangedocumentation_quarterlyaccessreview'),
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRemovalDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_from_external_system_date', models.DateTimeField(help_text='When the external-system account was deactivated or removed.')),
                ('removal_reason', models.TextField(help_text='Reason for removal (termination, role change, etc.)')),
                ('verified_removal', models.BooleanField(default=False, help_text='Indicates independent verification that removal is complete.')),
                ('verified_date', models.DateTimeField(blank=True, help_text='When verification occurred.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Supporting evidence links, ticket numbers, screenshots, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_removals_performed', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_documentation', to='access_management.usersystemaccess')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_removals_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Removal Documentation',
                'verbose_name_plural': 'Access Removal Documentation',
                'ordering': ['-removed_from_external_system_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyObsoleteAccountReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_month', models.CharField(help_text="Month reviewed (e.g., '2025-01')", max_length=10)),
                ('review_date', models.DateTimeField()),
                ('obsolete_accounts_identified', models.JSONField(blank=True, default=list, help_text='List or dict describing obsolete accounts identified.')),
                ('accounts_deactivated_in_external_systems', models.IntegerField(default=0)),
                ('accounts_pending_deactivation', models.IntegerField(default=0)),
                ('review_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional context, remediation steps, system owner confirmations.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_obsolete_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Obsolete Account Review',
                'verbose_name_plural': 'Monthly Obsolete Account Reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['review_month'], name='access_mana_review__793132_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyActiveUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_quarter', models.CharField(help_text="Quarter reviewed (e.g., '2025-Q1')", max_length=10)),
                ('review_date', models.DateTimeField()),
                ('total_active_users_in_external_system', models.IntegerField(help_text='Total active accounts discovered in the external system.')),
                ('approved_users_count', models.IntegerField(help_text='Count of accounts that matched approved access records.')),
                ('unapproved_users_count', models.IntegerField(help_text='Count of accounts found without an approved record.')),
                ('unapproved_users_list', models.TextField(blank=True, help_text='Details of unapproved accounts found (usernames, notes).', null=True)),
                ('discrepancies', models.TextField(blank=True, help_text='Document remediation steps or issues discovered.', null=True)),
                ('review_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_user_reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_active_user_reviews', to='systems.system')),
            ],
            options={
                'verbose_name': 'Quarterly Active User Review',
                'verbose_name_plural': 'Quarterly Active User Reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['review_quarter'], name='access_mana_review__c5e627_idx'), models.Index(fields=['system'], name='access_mana_system__70cac5_idx')],
            },
        ),
    ]
