# Generated by Django 5.2.8 on 2025-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0008_accessremovaldocumentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemaccess',
            name='license_category',
            field=models.CharField(blank=True, help_text='License category/SKU for email subscription mapping (e.g., E1, E3)', max_length=100, null=True),
        ),
    ]

