# Generated by Django 5.2.8 on 2026-01-31 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0012_usersystemaccess_license_category'),
        ('systems', '0009_systemcontracthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersystemaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who performed the soft-delete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_system_accesses_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='deleted_date',
            field=models.DateTimeField(blank=True, help_text='When the record was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for soft deletion', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Record is soft-deleted and should not appear in active queries'),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='lifecycle_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last status change', null=True),
        ),
        migrations.AddField(
            model_name='usersystemaccess',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='Last user who changed status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_number', models.IntegerField(help_text='Incremental instance number per user-system pair')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_instances_created', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_instances', to='systems.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_instances', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Access Instance',
                'verbose_name_plural': 'Access Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Sequential version number')),
                ('access_type', models.CharField(blank=True, max_length=50, null=True)),
                ('granted_access_level', models.CharField(blank=True, max_length=200, null=True)),
                ('permissions_added', models.JSONField(blank=True, default=list)),
                ('permissions_removed', models.JSONField(blank=True, default=list)),
                ('is_privilege_escalation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='access_management.accessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Version',
                'verbose_name_plural': 'Access Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(blank=True, max_length=50, null=True)),
                ('approvers_required', models.IntegerField(default=1)),
                ('approver_roles', models.JSONField(blank=True, default=list, help_text='Roles eligible to approve')),
                ('conflict_of_interest_rules', models.JSONField(blank=True, default=dict, help_text='COI rules like cannot_approve_self')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='systems.system')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('role_required', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_made', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='access_management.approvalstep')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Escalated', 'Escalated'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflows_created', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='access_management.approvalrule')),
                ('user_system_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='access_management.approvalworkflow'),
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='Attestation statement text')),
                ('attestation_date', models.DateTimeField(auto_now_add=True)),
                ('signature_method', models.CharField(choices=[('digital_certificate', 'Digital Certificate'), ('electronic_signature', 'Electronic Signature'), ('hmac', 'HMAC'), ('session', 'Authenticated Session')], default='session', max_length=50)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_made', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
            },
        ),
        migrations.CreateModel(
            name='AuditEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of audit event', max_length=100)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Event payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_event_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('event_hash', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('signature', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('signature_algorithm', models.CharField(default='HMAC-SHA256', max_length=50)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event Log',
                'verbose_name_plural': 'Audit Event Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('email', 'Email'), ('ticket', 'Ticket'), ('document', 'Document'), ('attestation', 'Attestation'), ('other', 'Other')], default='other', max_length=30)),
                ('file_artifact', models.FileField(blank=True, null=True, upload_to='evidence_artifacts/')),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 of file', max_length=128, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('access_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifacts', to='access_management.accessinstance')),
                ('access_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifacts', to='access_management.accessversion')),
                ('audit_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_artifacts', to='access_management.auditeventlog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_artifacts_created', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifacts', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Evidence Artifact',
                'verbose_name_plural': 'Evidence Artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accessinstance',
            index=models.Index(fields=['user', 'system', 'instance_number'], name='access_mana_user_id_206525_idx'),
        ),
        migrations.AddIndex(
            model_name='accessversion',
            index=models.Index(fields=['access_instance', 'version_number'], name='access_mana_access__5ac93a_idx'),
        ),
    ]
