# Generated by Django 5.2.6 on 2026-01-31 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0013_alter_usersystemaccess_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_frequency_days', models.IntegerField(default=90, help_text='Review interval in days')),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateTimeField()),
                ('review_completed', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalation_date', models.DateTimeField(blank=True, null=True)),
                ('escalated_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user_system_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='access_management.usersystemaccess')),
            ],
            options={
                'verbose_name': 'Access Review Schedule',
                'verbose_name_plural': 'Access Review Schedules',
                'ordering': ['next_review_date'],
            },
        ),
    ]
