# Generated by Django 5.2.8 on 2026-02-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0014_accessreviewschedule'),
        ('change_management', '0004_remove_accountchangerequest_chg_mgmt_owner_rejected_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemaccess',
            name='change_request',
            field=models.ForeignKey(blank=True, help_text='Associated change request in change management workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_assignments', to='change_management.accountchangerequest'),
        ),
    ]
