# Generated by Django 5.2.8 on 2025-11-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('Create', 'Create New Account in External System'), ('Modify', 'Modify Existing Account in External System'), ('Delete', 'Delete Account in External System'), ('Suspend', 'Suspend Account in External System')], help_text='Type of account change requested in the external system', max_length=20)),
                ('business_justification', models.TextField(help_text='Legitimate business need for this account change (RHG 4.4 requirement)')),
                ('system_owner_approved', models.BooleanField(default=False, help_text='System Owner has approved this change request')),
                ('system_owner_approval_date', models.DateTimeField(blank=True, help_text='When the System Owner approved this change request', null=True)),
                ('system_owner_approval_notes', models.TextField(blank=True, help_text='Notes from the System Owner regarding this change', null=True)),
                ('it_approval_date', models.DateTimeField(blank=True, help_text='When IT approved this change request', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed in External System')], default='Pending', help_text='Workflow status of the change request', max_length=20)),
                ('completed_in_external_system', models.BooleanField(default=False, help_text='True when the change has been implemented in the external system')),
                ('completed_date', models.DateTimeField(blank=True, help_text='When the change was completed in the external system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('it_approval', models.ForeignKey(blank=True, help_text='IT approver for this change request (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_approved_account_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Person requesting the account change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_change_requests_made', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(help_text='External system where the account change will occur (AD, PMS, POS, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='account_change_requests', to='systems.system')),
                ('system_owner', models.ForeignKey(blank=True, help_text='System Owner who must authorize the account change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_owner_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Employee whose account is being created/changed/deleted (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Change Request',
                'verbose_name_plural': 'Account Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
