# Generated by Django 5.2.8 on 2026-02-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_management', '0001_initial'),
        ('systems', '0009_systemcontracthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('modified', 'Modified'), ('viewed', 'Viewed'), ('exported', 'Exported')], help_text='Action performed', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Old field values (for modifications)')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New field values (for modifications)')),
                ('notes', models.TextField(blank=True, help_text='Additional context or notes', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent header (for web requests)', max_length=500)),
            ],
            options={
                'verbose_name': 'Change Audit Log',
                'verbose_name_plural': 'Change Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accountchangerequest',
            index=models.Index(fields=['status', '-created_at'], name='change_mana_status_bc6d82_idx'),
        ),
        migrations.AddIndex(
            model_name='accountchangerequest',
            index=models.Index(fields=['system', '-created_at'], name='change_mana_system__1db700_idx'),
        ),
        migrations.AddIndex(
            model_name='accountchangerequest',
            index=models.Index(fields=['user', '-created_at'], name='change_mana_user_id_2cd268_idx'),
        ),
        migrations.AddField(
            model_name='changeauditlog',
            name='change_request',
            field=models.ForeignKey(help_text='Reference to the change request', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='change_management.accountchangerequest'),
        ),
        migrations.AddField(
            model_name='changeauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='changeauditlog',
            index=models.Index(fields=['change_request', '-timestamp'], name='change_mana_change__1c6ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='changeauditlog',
            index=models.Index(fields=['performed_by', '-timestamp'], name='change_mana_perform_150440_idx'),
        ),
        migrations.AddIndex(
            model_name='changeauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='change_mana_action_12a9c4_idx'),
        ),
    ]
