# Generated by Django 5.2.8 on 2026-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_management', '0002_changeauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountchangerequest',
            name='user_full_name',
            field=models.CharField(blank=True, default='', help_text="Snapshot of user's full name at time of request creation (for audit trail if user is deleted)", max_length=255),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='user_username',
            field=models.CharField(blank=True, default='', help_text="Snapshot of user's username at time of request creation (for audit trail if user is deleted)", max_length=150),
        ),
    ]
