# Generated by Django 5.2.8 on 2026-02-10 14:21

from django.db import migrations


def populate_user_snapshots(apps, schema_editor):
    """
    Populate user_full_name and user_username fields from existing user data
    and UserArchive for deleted users.
    """
    AccountChangeRequest = apps.get_model('change_management', 'AccountChangeRequest')
    CustomUser = apps.get_model('accounts', 'CustomUser')
    UserArchive = apps.get_model('accounts', 'UserArchive')
    
    # Process all change requests with empty snapshot fields
    change_requests = AccountChangeRequest.objects.filter(
        user_full_name='',
        user_username=''
    )
    
    for cr in change_requests:
        if cr.user_id:
            # Try to get user from database
            try:
                user = CustomUser.objects.get(pk=cr.user_id)
                # Build full name from first and last name
                full_name = f"{user.first_name} {user.last_name}".strip()
                cr.user_full_name = full_name if full_name else user.username
                cr.user_username = user.username
                cr.save(update_fields=['user_full_name', 'user_username'])
            except CustomUser.DoesNotExist:
                # User was deleted, try to find in archive
                archives = UserArchive.objects.filter(source_user_id=cr.user_id).order_by('-archived_at')
                if archives.exists():
                    archive = archives.first()
                    cr.user_full_name = archive.full_name or archive.username
                    cr.user_username = archive.username
                    cr.save(update_fields=['user_full_name', 'user_username'])


def reverse_populate(apps, schema_editor):
    """
    Reverse migration - clear snapshot fields
    """
    AccountChangeRequest = apps.get_model('change_management', 'AccountChangeRequest')
    AccountChangeRequest.objects.all().update(
        user_full_name='',
        user_username=''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('change_management', '0003_accountchangerequest_user_full_name_and_more'),
        ('accounts', '0001_initial'),  # Ensure accounts app is migrated
    ]

    operations = [
        migrations.RunPython(populate_user_snapshots, reverse_populate),
    ]
