# Generated by Django 5.2.8 on 2026-02-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_management', '0003_add_rejection_tracking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountchangerequest',
            name='chg_mgmt_owner_rejected_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountchangerequest',
            name='chg_mgmt_it_rejected_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountchangerequest',
            name='chg_mgmt_status_owner_rejected_idx',
        ),
    ]
