# Generated by Django 5.2.8 on 2026-02-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_management', '0004_populate_user_snapshots'),
        ('systems', '0009_systemcontracthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchangerequest',
            name='system',
            field=models.ForeignKey(blank=True, help_text='External system where the account change will occur (AD, PMS, POS, etc.). Null for corporate-level changes like user deletion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_change_requests', to='systems.system'),
        ),
    ]
