# Generated by Django 5.2.8 on 2025-11-10 11:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(help_text='Unique employee identifier (e.g., EMP001, 2024-001)', max_length=50, unique=True)),
                ('national_id', models.CharField(blank=True, help_text='Government ID number (encrypted in database)', max_length=50, null=True)),
                ('phone_primary', models.CharField(help_text='Primary phone number (international format)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in international format.', regex='^\\+?1?\\d{9,15}$')])),
                ('phone_secondary', models.CharField(blank=True, help_text='Secondary phone number (optional)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in international format.', regex='^\\+?1?\\d{9,15}$')])),
                ('personal_email', models.EmailField(blank=True, help_text='Personal email address (different from work email)', max_length=254, null=True)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Consultant', 'Consultant')], default='Full-time', max_length=20)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('position', models.CharField(help_text='Job title or position', max_length=200)),
                ('job_title', models.CharField(blank=True, help_text='Alternative field for job title', max_length=200, null=True)),
                ('join_date', models.DateField(help_text='Employee start date')),
                ('end_date', models.DateField(blank=True, help_text='For terminated/resigned employees', null=True)),
                ('probation_end_date', models.DateField(blank=True, help_text='End of probation period', null=True)),
                ('employee_level', models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive')], default='Entry', max_length=20)),
                ('office_location', models.CharField(default='Headquarters', help_text='Office location (e.g., Headquarters, Branch A, Remote)', max_length=200)),
                ('office_room', models.CharField(blank=True, help_text='Room or desk number', max_length=50, null=True)),
                ('work_address', models.TextField(blank=True, help_text='Full work address', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile photo (max 2MB, JPG/PNG formats)', null=True, upload_to='profiles/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='For birthday reminders', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the user (not visible to regular users)', null=True)),
                ('ad_username', models.CharField(blank=True, help_text='Active Directory username', max_length=100, null=True)),
                ('ad_synced', models.BooleanField(default=False, help_text='True when synced from Active Directory')),
                ('last_ad_sync', models.DateTimeField(blank=True, help_text='Timestamp of last AD sync', null=True)),
                ('ad_distinguished_name', models.CharField(blank=True, help_text='Full AD DN path', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
