# Generated by Django 5.2.8 on 2025-11-10 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Employee start date'),
        ),
    ]
