# Generated by Django 5.2.8 on 2025-11-13 10:49

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique employee identifier generated by the system', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (max 2MB, JPG/PNG formats)', null=True, upload_to='profiles/', validators=[accounts.models.CustomUser._validate_profile_photo]),
        ),
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('department_name', models.CharField(blank=True, max_length=200)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_archives_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived User',
                'verbose_name_plural': 'Archived Users',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDeactivationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=150)),
                ('user_full_name', models.CharField(blank=True, max_length=255)),
                ('user_employee_id', models.CharField(blank=True, max_length=50)),
                ('deactivated_at', models.DateTimeField(auto_now_add=True)),
                ('system_confirmed', models.BooleanField(default=False)),
                ('hardware_confirmed', models.BooleanField(default=False)),
                ('hardware_status_action', models.CharField(default='no_change', max_length=20)),
                ('system_assignments', models.JSONField(blank=True, default=list)),
                ('hardware_assignments', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivation_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivation_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Deactivation Audit',
                'verbose_name_plural': 'User Deactivation Audits',
                'ordering': ['-deactivated_at'],
            },
        ),
    ]
