# Generated by Django 5.2.8 on 2025-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, help_text='User description (visible to users)', null=True),
        ),
    ]
