# Generated by Django 5.2.8 on 2025-11-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_it_administrator',
            field=models.BooleanField(default=False, help_text='User is authorized as IT Administrator (RHG 4.3 scope)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='it_admin_certification_date',
            field=models.DateField(blank=True, help_text='Date the user was certified/authorized as IT Administrator', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='it_admin_certified_by',
            field=models.ForeignKey(blank=True, help_text='Who approved the user as IT Administrator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_admin_certifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
