# Generated by Django 5.2.8 on 2025-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_it_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flag_for_follow_up',
            field=models.BooleanField(default=False, help_text='Mark when this user needs a manual follow-up'),
        ),
    ]
