# Generated by Django 5.2.8 on 2025-11-25 11:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_flag_for_follow_up'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='exclude_from_metrics',
            field=models.BooleanField(default=False, help_text='Exclude this account from total user counts and dashboards'),
        ),
    ]
