# Generated by Django 5.2.8 on 2025-11-27 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_enabled', models.BooleanField(default=False, help_text='Enable LDAP authentication')),
                ('is_active_directory', models.BooleanField(default=True, help_text='This is an Active Directory server')),
                ('cache_passwords', models.BooleanField(default=True, help_text="Cache LDAP passwords as local hashed passwords. Uncheck if you don't want to keep LDAP passwords cached.")),
                ('ad_domain', models.CharField(blank=True, help_text='Active Directory domain (sometimes the same as email domain)', max_length=255)),
                ('ldap_client_tls_key', models.TextField(blank=True, help_text='LDAP Client-Side TLS Key (usually for Google Workspace Secure LDAP)')),
                ('ldap_client_tls_cert', models.TextField(blank=True, help_text='LDAP Client-Side TLS Certificate (usually for Google Workspace Secure LDAP)')),
                ('ldap_server', models.CharField(default='ldap://ldap.example.com:389', help_text='LDAP Server URL (ldap:// for unencrypted or ldaps:// for TLS/SSL)', max_length=500)),
                ('use_tls', models.BooleanField(default=False, help_text='Use STARTTLS for LDAP connection')),
                ('allow_invalid_ssl', models.BooleanField(default=False, help_text='Allow invalid SSL certificates (for self-signed certificates)')),
                ('bind_username', models.CharField(blank=True, help_text='LDAP Bind Username (full DN or UPN format)', max_length=500)),
                ('bind_password', models.CharField(blank=True, help_text='LDAP Bind Password', max_length=500)),
                ('base_dn', models.CharField(blank=True, help_text='Base Bind DN (e.g., DC=example,DC=com)', max_length=500)),
                ('ldap_filter', models.CharField(blank=True, default='(&(objectClass=user)(objectCategory=person))', help_text='LDAP Filter for user search', max_length=500)),
                ('ldap_auth_query', models.CharField(blank=True, help_text='LDAP Authentication query', max_length=500)),
                ('ldap_username_field', models.CharField(default='samaccountname', help_text='LDAP Username Field (use lowercase for AD: samaccountname)', max_length=100)),
                ('ldap_lastname_field', models.CharField(default='sn', help_text='LDAP Last Name Field', max_length=100)),
                ('ldap_firstname_field', models.CharField(default='givenname', help_text='LDAP First Name Field (use lowercase: givenname)', max_length=100)),
                ('ldap_displayname_field', models.CharField(blank=True, default='displayname', help_text='LDAP Display Name Field (use lowercase: displayname)', max_length=100)),
                ('ldap_employeenumber_field', models.CharField(blank=True, default='employeenumber', help_text='LDAP Employee Number Field', max_length=100)),
                ('ldap_department_field', models.CharField(blank=True, default='department', help_text='LDAP Department Field', max_length=100)),
                ('ldap_manager_field', models.CharField(blank=True, default='manager', help_text='LDAP Manager Field (DN of manager)', max_length=100)),
                ('ldap_email_field', models.CharField(default='mail', help_text='LDAP Email Field', max_length=100)),
                ('ldap_phone_field', models.CharField(blank=True, default='telephonenumber', help_text='LDAP Phone Number Field', max_length=100)),
                ('ldap_mobile_field', models.CharField(blank=True, default='mobile', help_text='LDAP Mobile Field', max_length=100)),
                ('ldap_jobtitle_field', models.CharField(blank=True, default='title', help_text='LDAP Job Title Field', max_length=100)),
                ('ldap_address_field', models.CharField(blank=True, default='streetaddress', help_text='LDAP Address Field', max_length=100)),
                ('ldap_city_field', models.CharField(blank=True, default='l', help_text='LDAP City Field', max_length=100)),
                ('ldap_state_field', models.CharField(blank=True, default='st', help_text='LDAP State/Province Field', max_length=100)),
                ('ldap_postalcode_field', models.CharField(blank=True, default='postalcode', help_text='LDAP Postal Code Field', max_length=100)),
                ('ldap_country_field', models.CharField(blank=True, default='co', help_text='LDAP Country Field', max_length=100)),
                ('ldap_location_field', models.CharField(blank=True, default='', help_text='LDAP Location Field (if not using OU in Base Bind DN)', max_length=100)),
                ('ldap_active_flag', models.CharField(blank=True, default='useraccountcontrol', help_text='LDAP Active Flag field (userAccountControl for AD)', max_length=100)),
                ('ldap_invert_active_flag', models.BooleanField(default=False, help_text='Invert the active flag logic (enabled when value is 0 or false)')),
                ('custom_password_reset_url', models.URLField(blank=True, help_text='Custom password reset URL for LDAP users', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_permission_group', models.ForeignKey(blank=True, help_text='Default permission group for new LDAP users', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldap_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
                'verbose_name_plural': 'LDAP Configurations',
            },
        ),
    ]
