# Generated by Django 5.2.8 on 2026-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_ldap_bind_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exclude_from_ldap_sync',
            field=models.BooleanField(default=False, help_text='Exclude this user from LDAP synchronization'),
        ),
    ]
