# Generated by Django 5.2.8 on 2026-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_exclude_from_ldap_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarchive',
            name='exclude_from_ldap_sync',
            field=models.BooleanField(default=True, help_text='Prevent this archived user from being re-synced from LDAP'),
        ),
    ]
