# Generated by Django 5.2.8 on 2025-11-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly asset name (e.g., Finance-SQL01, John Doe Laptop).', max_length=255)),
                ('asset_tag', models.CharField(help_text='Unique organizational asset tag or inventory ID.', max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer serial number (if available).', max_length=100, null=True, unique=True)),
                ('hardware_type', models.CharField(choices=[('Desktop', 'Desktop PC'), ('Laptop', 'Laptop'), ('Server', 'Server'), ('Virtual Server', 'Virtual Server'), ('Network Device', 'Network Device'), ('Peripheral', 'Peripheral / Accessory'), ('Mobile Device', 'Mobile Device / Tablet'), ('Storage', 'Storage Device'), ('Other', 'Other')], default='Desktop', help_text='Primary hardware classification.', max_length=50)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('Provisioning', 'Provisioning'), ('In Repair', 'In Repair'), ('In Storage', 'In Storage'), ('Retired', 'Retired'), ('Disposed', 'Disposed')], default='In Service', help_text='Lifecycle status for this asset.', max_length=20)),
                ('manufacturer', models.CharField(blank=True, help_text='Asset manufacturer/vendor (e.g., Dell, HP, Cisco).', max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, help_text='Model or SKU identifier.', max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text='Installed operating system (if applicable).', max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, help_text='CPU specification (e.g., Intel i7-1165G7).', max_length=100, null=True)),
                ('memory_gb', models.PositiveIntegerField(blank=True, help_text='Installed memory in GB.', null=True)),
                ('storage_capacity_gb', models.PositiveIntegerField(blank=True, help_text='Total storage capacity in GB.', null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Date the asset was purchased or leased.', null=True)),
                ('warranty_expiration', models.DateField(blank=True, help_text='Warranty end date.', null=True)),
                ('end_of_life_date', models.DateField(blank=True, help_text='Planned end-of-life date for budgeting/replacement.', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location (e.g., HQ - 3rd Floor - Rack 4).', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Primary IP address assigned to the asset.', null=True)),
                ('mac_address', models.CharField(blank=True, help_text='Primary MAC address.', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional comments, configuration details, or history.', null=True)),
                ('is_virtual', models.BooleanField(default=False, help_text='Indicates if the asset is virtualized (VM, container, etc.).')),
                ('requires_patch_management', models.BooleanField(default=True, help_text='Whether the asset participates in patch management cycles.')),
                ('last_inventory_check', models.DateField(blank=True, help_text='Last date the asset was physically verified.', null=True)),
                ('next_inventory_check', models.DateField(blank=True, help_text='Scheduled next verification date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Additional users who use or share this asset.', related_name='hardware_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Owning or primary department responsible for this asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_assets', to='departments.department')),
                ('primary_user', models.ForeignKey(blank=True, help_text='Primary user that the asset is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_hardware_assets', to=settings.AUTH_USER_MODEL)),
                ('related_systems', models.ManyToManyField(blank=True, help_text='Systems or applications hosted on or associated with this asset.', related_name='hardware_assets', to='systems.system')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hardware Asset',
                'verbose_name_plural': 'Hardware Assets',
                'ordering': ['name', 'asset_tag'],
                'unique_together': {('name', 'asset_tag')},
            },
        ),
    ]
