# Generated by Django 5.2.8 on 2026-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareasset',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, help_text='Primary IPv4 address (if available).', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Indicates if the associated directory/computer account is enabled.'),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='operating_system_version',
            field=models.CharField(blank=True, help_text='Operating system version / build (e.g., 10.0.19045).', max_length=100, null=True),
        ),
    ]
