# Generated by Django 5.2.8 on 2026-02-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_hardwareasset_ipv4_address_hardwareasset_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hardwareasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='local_asset_tag',
            field=models.CharField(blank=True, help_text='Local asset tag or secondary inventory ID.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='tm_id',
            field=models.CharField(blank=True, help_text='TM ID for asset tracking (if applicable).', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hardwareasset',
            unique_together={('name', 'asset_tag', 'tm_id', 'local_asset_tag')},
        ),
    ]
