# Generated by Django 5.2.8 on 2026-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_hardwareasset_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareasset',
            name='is_sync_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, LDAP sync will update this asset. Disable to manually manage this asset.'),
        ),
    ]
