# Generated by Django 5.2.8 on 2026-02-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('hardware', '0004_hardwareasset_is_sync_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Accessory name (e.g., Dell 27-inch Monitor, Logitech MX Master).', max_length=255)),
                ('accessory_type', models.CharField(choices=[('Monitor', 'Monitor / Display'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse / Pointing Device'), ('Dock', 'Docking Station'), ('Headset', 'Headset / Speakers'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('External Storage', 'External Storage / Drive'), ('USB Hub', 'USB Hub'), ('Cable', 'Cable / Connector'), ('Power Supply', 'Power Supply / Adapter'), ('Camera', 'Webcam / Camera'), ('Other', 'Other Accessory')], default='Monitor', help_text='Type of accessory.', max_length=50)),
                ('asset_tag', models.CharField(help_text='Unique asset tag or inventory ID for this accessory.', max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer serial number (if available).', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('In Repair', 'In Repair'), ('In Storage', 'In Storage'), ('Retired', 'Retired'), ('Disposed', 'Disposed')], default='In Service', help_text='Lifecycle status for this accessory.', max_length=20)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer/vendor (e.g., Dell, Logitech, HP).', max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, help_text='Model or SKU identifier.', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Date the accessory was purchased or leased.', null=True)),
                ('warranty_expiration', models.DateField(blank=True, help_text='Warranty end date.', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location (e.g., HQ - 3rd Floor - Desk 12).', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional comments or specifications.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department responsible for this accessory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='departments.department')),
                ('primary_user', models.ForeignKey(blank=True, help_text='Primary user assigned to this accessory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_accessories', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'ordering': ['name', 'asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='RelatedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('Primary', 'Primary Assignment'), ('Shared', 'Shared / Temporary'), ('Backup', 'Backup'), ('Optional', 'Optional / Extra')], default='Primary', help_text='Type of assignment relationship.', max_length=20)),
                ('assignment_date', models.DateField(auto_now_add=True, help_text='Date the accessory was assigned to this hardware.')),
                ('removal_date', models.DateField(blank=True, help_text='Date the accessory was removed from this hardware (if applicable).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional assignment notes or history.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(help_text='The accessory (e.g., monitor, keyboard) being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='hardware_assignments', to='hardware.accessory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_assets_created', to=settings.AUTH_USER_MODEL)),
                ('hardware_asset', models.ForeignKey(help_text='The hardware asset (e.g., desktop, laptop) this accessory is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='related_accessories', to='hardware.hardwareasset')),
            ],
            options={
                'verbose_name': 'Related Asset',
                'verbose_name_plural': 'Related Assets',
                'ordering': ['-assignment_date'],
                'unique_together': {('hardware_asset', 'accessory')},
            },
        ),
    ]
