# Generated by Django 5.2.8 on 2026-02-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardOperatingProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="SOP title, e.g. 'User Account Creation Process'", max_length=255)),
                ('version', models.CharField(help_text="Document version identifier, e.g. 'v1.0', '2025-Q4'", max_length=50)),
                ('content', models.TextField(help_text='Full SOP content in markdown or rich text form')),
                ('approved_date', models.DateTimeField(blank=True, help_text='When this SOP version was approved', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark as active to show this SOP in current procedures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Person who approved this SOP version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standard Operating Procedure',
                'verbose_name_plural': 'Standard Operating Procedures',
                'ordering': ['title', '-created_at'],
            },
        ),
    ]
