# Generated by Django 5.2.8 on 2025-11-18 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="Default account name (e.g., 'admin', 'supervisor', 'Opera').", max_length=200)),
                ('account_type', models.CharField(choices=[('Database', 'Database Default Account'), ('Workstation', 'Workstation Image / Local Account'), ('Server', 'Server / ILO Default Account'), ('Application', 'Application / PMS Default Account'), ('Network Device', 'Network Device (Switch/Firewall) Account'), ('Printer', 'Printer / Peripheral Default Account'), ('Other', 'Other Default Account')], default='Application', max_length=25)),
                ('status', models.CharField(choices=[('Pending', 'Pending Reset/Removal'), ('Active - Password Changed', 'Active - Password Changed in External System'), ('Removed', 'Removed from External System'), ('Not Applicable', 'Not Applicable (Hosted / No Access)'), ('In Review', 'Under Review / Follow-up Needed')], default='Pending', help_text='Current remediation status for this default account.', max_length=40)),
                ('password_changed_in_external_system', models.BooleanField(default=False, help_text='Password was changed in the external system per RHG policy.')),
                ('password_changed_date', models.DateTimeField(blank=True, help_text='Date password was changed in the external system.', null=True)),
                ('password_change_reference', models.CharField(blank=True, help_text='Ticket/screenshot/reference ID for password change evidence.', max_length=255)),
                ('password_change_notes', models.TextField(blank=True, help_text='Notes describing how password change was executed.', null=True)),
                ('removal_required', models.BooleanField(default=True, help_text='Whether this default account must ultimately be removed.')),
                ('removed_from_external_system', models.BooleanField(default=False, help_text='Account was fully removed from the external system.')),
                ('removal_date', models.DateTimeField(blank=True, help_text='Date removal was completed.', null=True)),
                ('removal_reference', models.CharField(blank=True, help_text='Ticket/screenshot reference for removal evidence.', max_length=255)),
                ('remediation_notes', models.TextField(blank=True, help_text='Narrative on how this default account was handled/remediated.', null=True)),
                ('installation_checklist_completed', models.BooleanField(default=False, help_text='Installation checklist completed for this account/system.')),
                ('installation_checklist_completed_date', models.DateTimeField(blank=True, null=True)),
                ('installation_notes', models.TextField(blank=True, help_text='Notes captured during new system installation.', null=True)),
                ('last_verified_date', models.DateTimeField(blank=True, help_text='Last time evidence was verified.', null=True)),
                ('verification_artifact', models.CharField(blank=True, help_text='Link or identifier for verification artifact (screenshot/ticket).', max_length=255)),
                ('hosted_not_applicable_reason', models.CharField(blank=True, help_text='Document why the account is not applicable (e.g., hosted solution).', max_length=255)),
                ('is_rhg_special_account', models.BooleanField(default=False, help_text='Tracks RHG-specific legacy accounts (e.g., michael.brandt).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('installation_documented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_account_installations', to=settings.AUTH_USER_MODEL)),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_account_verifications', to=settings.AUTH_USER_MODEL)),
                ('password_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_account_password_changes', to=settings.AUTH_USER_MODEL)),
                ('removal_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_account_removal_confirmations', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(help_text='External system this default account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='default_accounts', to='systems.system')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Default Account',
                'verbose_name_plural': 'Default Accounts',
                'ordering': ['system__name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='DefaultAccountAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('password_reset', 'Password Reset / Changed in External System'), ('removal', 'Removed / Disabled in External System'), ('mark_not_applicable', 'Marked Not Applicable'), ('installation_checklist', 'Installation Checklist Completed'), ('verification', 'Verification / Evidence Capture'), ('note', 'Documentation / Notes Update')], max_length=40)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this action occurred in the external system.')),
                ('evidence_reference', models.CharField(blank=True, help_text='Ticket ID / screenshot file / vendor confirmation reference.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Narrative documentation of what was performed.', null=True)),
                ('status_applied', models.CharField(blank=True, choices=[('Pending', 'Pending Reset/Removal'), ('Active - Password Changed', 'Active - Password Changed in External System'), ('Removed', 'Removed from External System'), ('Not Applicable', 'Not Applicable (Hosted / No Access)'), ('In Review', 'Under Review / Follow-up Needed')], help_text='Optional override to set the parent record status directly.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='default_accounts.defaultaccount')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_account_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Default Account Action',
                'verbose_name_plural': 'Default Account Actions',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='DefaultAccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(default='Any', help_text="Matches the `system_type` field on `System` (use 'Any' for all systems).", max_length=50)),
                ('account_name', models.CharField(help_text='Default account name in the external system (e.g., admin, supervisor).', max_length=200)),
                ('account_type', models.CharField(choices=[('Database', 'Database Default Account'), ('Workstation', 'Workstation Image / Local Account'), ('Server', 'Server / ILO Default Account'), ('Application', 'Application / PMS Default Account'), ('Network Device', 'Network Device (Switch/Firewall) Account'), ('Printer', 'Printer / Peripheral Default Account'), ('Other', 'Other Default Account')], default='Application', max_length=25)),
                ('description', models.TextField(blank=True, help_text='Context on where this default account is normally seen.', null=True)),
                ('removal_required', models.BooleanField(default=True, help_text='If true, remediation expects removal once system is installed.')),
                ('applies_to_all', models.BooleanField(default=False, help_text='When enabled this template is instantiated for every new system automatically.')),
                ('rhg_special_account', models.BooleanField(default=False, help_text='Flag for RHG-specific accounts (e.g., michael.brandt).')),
                ('default_status', models.CharField(choices=[('Pending', 'Pending Reset/Removal'), ('Active - Password Changed', 'Active - Password Changed in External System'), ('Removed', 'Removed from External System'), ('Not Applicable', 'Not Applicable (Hosted / No Access)'), ('In Review', 'Under Review / Follow-up Needed')], default='Pending', help_text='Initial status assigned when this template is applied.', max_length=40)),
                ('notes', models.TextField(blank=True, help_text='Additional notes/checklist instructions.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Account Template',
                'verbose_name_plural': 'Default Account Templates',
                'ordering': ['system_type', 'account_name'],
                'unique_together': {('system_type', 'account_name')},
            },
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantiated_accounts', to='default_accounts.defaultaccounttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultaccount',
            unique_together={('system', 'account_name')},
        ),
    ]
