# Generated by Django 5.2.8 on 2025-11-18 12:22

from django.db import migrations


FALLBACK_TEMPLATE_DATA = [
    # Databases
    {
        "system_type": "Database",
        "account_name": "Opera",
        "account_type": "Database",
        "removal_required": True,
        "notes": "Opera PMS database master account. Must be removed or rotated.",
    },
    {
        "system_type": "Database",
        "account_name": "SYS",
        "account_type": "Database",
        "removal_required": True,
        "notes": "Oracle SYS account. Track password rotation and lockdown.",
    },
    {
        "system_type": "Database",
        "account_name": "VISION",
        "account_type": "Database",
        "removal_required": True,
        "notes": "Vision/accounting platform default account.",
    },
    # PMS / Application defaults
    {
        "system_type": "Desktop Application",
        "account_name": "supervisor",
        "account_type": "Application",
        "removal_required": True,
        "notes": "PMS supervisor ID included in hotel images.",
    },
    {
        "system_type": "Desktop Application",
        "account_name": "Interface",
        "account_type": "Application",
        "removal_required": True,
        "notes": "PMS interface connector account.",
    },
    # Workstation images
    {
        "system_type": "Operating System",
        "account_name": "LocalAdmin",
        "account_type": "Workstation",
        "removal_required": True,
        "notes": "Local administrator password must be rotated from imaging defaults.",
    },
    {
        "system_type": "Operating System",
        "account_name": "Technician",
        "account_type": "Workstation",
        "removal_required": True,
        "notes": "Pre-build tech account found on workstation images.",
    },
    # Servers / ILO
    {
        "system_type": "Operating System",
        "account_name": "Administrator",
        "account_type": "Server",
        "removal_required": True,
        "notes": "Windows Server default Administrator credential.",
    },
    {
        "system_type": "Other",
        "account_name": "ILO",
        "account_type": "Server",
        "removal_required": True,
        "notes": "ILO / out-of-band interface default login.",
    },
    # Network & printers
    {
        "system_type": "Network Device",
        "account_name": "admin",
        "account_type": "Network Device",
        "removal_required": True,
        "notes": "Generic admin account present on switches/routers.",
    },
    {
        "system_type": "Network Device",
        "account_name": "cisco",
        "account_type": "Network Device",
        "removal_required": True,
        "notes": "Cisco factory default credential.",
    },
    {
        "system_type": "Other",
        "account_name": "printer_admin",
        "account_type": "Printer",
        "removal_required": True,
        "notes": "Common printer admin password (7777) must be rotated.",
    },
    # RHG accounts
    {
        "system_type": "Any",
        "account_name": "michael.brandt",
        "account_type": "Application",
        "removal_required": True,
        "applies_to_all": True,
        "rhg_special_account": True,
        "notes": "Legacy RHG corporate account flagged for removal everywhere.",
    },
    {
        "system_type": "Any",
        "account_name": "roger.bergh",
        "account_type": "Application",
        "removal_required": True,
        "applies_to_all": True,
        "rhg_special_account": True,
        "notes": "Legacy RHG corporate account flagged for removal everywhere.",
    },
    # Hosted exception
    {
        "system_type": "Cloud Service",
        "account_name": "EMMA Database Root",
        "account_type": "Database",
        "removal_required": False,
        "default_status": "Not Applicable",
        "notes": "EMMA is hosted; hotels have no database access. Document as N/A.",
    },
]


def seed_templates(apps, schema_editor):
    Template = apps.get_model('default_accounts', 'DefaultAccountTemplate')
    for entry in FALLBACK_TEMPLATE_DATA:
        lookup = {
            'system_type': entry['system_type'],
            'account_name': entry['account_name'],
        }
        defaults = entry.copy()
        defaults.setdefault('default_status', 'Pending')
        defaults.pop('system_type')
        defaults.pop('account_name')
        Template.objects.update_or_create(defaults=defaults, **lookup)


class Migration(migrations.Migration):

    dependencies = [
        ('default_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
