# Generated by Django 5.2.8 on 2025-12-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_accounts', '0004_change_template_to_many_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccounttemplate',
            name='applies_to_all',
            field=models.BooleanField(default=False, help_text='When enabled this template is instantiated for every new system automatically. Use with no systems selected for global templates.'),
        ),
    ]
