# Generated by Django 5.2.8 on 2025-11-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (must be unique)', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Department code (e.g., IT, HR, FIN-ACC)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the department', null=True)),
                ('department_type', models.CharField(choices=[('Division', 'Division'), ('Department', 'Department'), ('Team', 'Team'), ('Unit', 'Unit')], default='Department', help_text='Type of organizational unit', max_length=20)),
                ('cost_center', models.CharField(blank=True, help_text='Cost center code', max_length=50, null=True)),
                ('budget_code', models.CharField(blank=True, help_text='Budget allocation code', max_length=50, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Physical office location', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, help_text='Department contact phone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Department contact email', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active')),
                ('established_date', models.DateField(blank=True, help_text='Date when department was established', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL)),
                ('head_of_department', models.ForeignKey(blank=True, help_text='Department head/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department (NULL for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
    ]
