# Generated by Django 5.2.8 on 2025-11-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="Account name in the external system (e.g., 'svc_backup' in AD)", max_length=200)),
                ('account_type', models.CharField(choices=[('Service', 'Service/Application Account'), ('Interface', 'Interface Account'), ('Backup', 'Backup Account'), ('Privileged', 'Privileged/Admin Account')], default='Service', help_text='Type of service account', max_length=20)),
                ('purpose', models.TextField(help_text="What it's for - documented purpose of the service account")),
                ('password_last_changed', models.DateTimeField(blank=True, help_text='Last password change date in the external system', null=True)),
                ('password_expires_on', models.DateTimeField(blank=True, help_text='Password expiration date in the external system', null=True)),
                ('password_complies_with_policy', models.BooleanField(default=False, help_text='Documented compliance with RHG password policy in external system')),
                ('password_policy_verified_date', models.DateTimeField(blank=True, help_text='Date when password policy compliance was verified', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service account is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the service account', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Account owner/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_service_accounts', to=settings.AUTH_USER_MODEL)),
                ('password_policy_verified_by', models.ForeignKey(blank=True, help_text='User who verified password policy compliance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_policy_verifications', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(help_text='Which external system (AD, Opera Cloud, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='systems.system')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Account',
                'verbose_name_plural': 'Service Accounts',
                'ordering': ['system', 'account_name'],
                'unique_together': {('account_name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='ServiceAccountPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_changed_date', models.DateTimeField(help_text='Date password was changed in the external system')),
                ('documented_at', models.DateTimeField(auto_now_add=True, help_text='When it was documented in this system')),
                ('expires_on', models.DateTimeField(blank=True, help_text='Password expiration date', null=True)),
                ('complies_with_policy', models.BooleanField(default=True, help_text='Whether password complies with RHG policy')),
                ('notes', models.TextField(blank=True, help_text='Notes about the password change', null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Who documented the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_account_password_changes', to=settings.AUTH_USER_MODEL)),
                ('service_account', models.ForeignKey(help_text='Service account this password change belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='service_accounts.serviceaccount')),
            ],
            options={
                'verbose_name': 'Service Account Password History',
                'verbose_name_plural': 'Service Account Password History',
                'ordering': ['-password_changed_date'],
            },
        ),
    ]
