# Generated by Django 5.2.8 on 2025-11-18 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='Administrator (4.3) this privileged account maps back to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_service_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='change_request_id',
            field=models.CharField(blank=True, help_text='Reference to change ticket that established/rotated this account', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='is_privileged',
            field=models.BooleanField(default=False, help_text='Marks if this service account should be governed as privileged/admin'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_attestation_notes',
            field=models.TextField(blank=True, help_text='Notes collected during last attestation (purpose, storage evidence, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_attestation_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed in Use'), ('Pending Removal', 'Pending Removal'), ('Unknown', 'Unknown / Needs Review')], default='Unknown', help_text='Outcome of the latest attestation', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_attested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of latest owner attestation', null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_attested_by',
            field=models.ForeignKey(blank=True, help_text='Owner/approver who completed the latest attestation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_account_attestations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='password_storage_location',
            field=models.CharField(blank=True, help_text='Location of the password (vault/safe/manager)', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='sop_reference',
            field=models.CharField(blank=True, help_text="Referenced SOP covering this account's use/rotation", max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceAccountAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attested_at', models.DateTimeField(auto_now_add=True, help_text='When the attestation was captured')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed in Use'), ('Pending Removal', 'Pending Removal'), ('Unknown', 'Unknown / Needs Review')], default='Confirmed', help_text='Attestation result', max_length=20)),
                ('storage_location', models.CharField(blank=True, help_text='Password storage location confirmed during attestation', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional evidence or commentary', null=True)),
                ('attested_by', models.ForeignKey(blank=True, help_text='Who attested/approved', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_account', models.ForeignKey(help_text='Service account being attested', on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='service_accounts.serviceaccount')),
            ],
            options={
                'verbose_name': 'Service Account Attestation',
                'verbose_name_plural': 'Service Account Attestations',
                'ordering': ['-attested_at'],
            },
        ),
    ]
