"""
Django settings for user_access_management project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

try:
    import dj_database_url  # type: ignore
except Exception:
    dj_database_url = None

try:
    import sentry_sdk  # type: ignore
    from sentry_sdk.integrations.django import DjangoIntegration  # type: ignore
except Exception:
    sentry_sdk = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be provided via environment and not fall back to a default.
SECRET_KEY = config('SECRET_KEY', default='django-insecure-development-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]) or []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'accounts',
    'departments',
    'systems',
    'access_management',
    'dashboard',
    'data_import_export',
    'hardware',
    'service_accounts',
    'change_management',
    'documentation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Optional WhiteNoise for serving static files in production
    # Enable via USE_WHITENOISE=true
    *(
        ['whitenoise.middleware.WhiteNoiseMiddleware']
        if config('USE_WHITENOISE', default=False, cast=bool)
        else []
    ),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'user_access_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_access_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If DATABASE_URL is provided, use it (e.g., for Postgres in production)
DATABASE_URL = config('DATABASE_URL', default='')
if DATABASE_URL and dj_database_url:
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
else:
    # Allow configuration via individual POSTGRES_* variables when DJANGO_DB=postgres
    DJANGO_DB = config('DJANGO_DB', default='sqlite')
    if DJANGO_DB.lower() == 'postgres':
        pg_db = config('POSTGRES_DB', default='postgres')
        pg_user = config('POSTGRES_USER', default='postgres')
        pg_password = config('POSTGRES_PASSWORD', default='')
        pg_host = config('POSTGRES_HOST', default='localhost')
        pg_port = config('POSTGRES_PORT', default='5432')
        if dj_database_url:
            url = f"postgres://{pg_user}:{pg_password}@{pg_host}:{pg_port}/{pg_db}"
            DATABASES['default'] = dj_database_url.parse(url, conn_max_age=600)
        else:
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': pg_db,
                'USER': pg_user,
                'PASSWORD': pg_password,
                'HOST': pg_host,
                'PORT': pg_port,
            }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Directory for collectstatic (production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage for gzip/brotli in production when enabled
if config('USE_WHITENOISE', default=False, cast=bool):
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Custom Admin Site
ADMIN_SITE_HEADER = "User Access Management System"
ADMIN_SITE_TITLE = "UAMS Admin"
ADMIN_INDEX_TITLE = "Welcome to User Access Management System"

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard_home'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Email settings
# For production, configure real SMTP in environment variables.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@user-access-management.local')
ADMINS = config(
    'ADMINS',
    default='IT Security <it.security@example.com>',
    cast=lambda v: [tuple(part.strip().rsplit(' ', 1)) for part in [v] if v],
)

# Security hardening when not in DEBUG
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')
    SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='same-origin')

# Basic logging configuration
LOG_LEVEL = config('LOG_LEVEL', default='INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}

# Optional Sentry integration (set SENTRY_DSN to enable)
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN and sentry_sdk:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(config('SENTRY_TRACES_SAMPLE_RATE', default='0.0')),
        profiles_sample_rate=float(config('SENTRY_PROFILES_SAMPLE_RATE', default='0.0')),
        send_default_pii=config('SENTRY_SEND_DEFAULT_PII', default=False, cast=bool),
        environment=config('SENTRY_ENVIRONMENT', default='production' if not DEBUG else 'development'),
    )
