# Generated by Django 5.2.8 on 2025-11-10 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='System name (must be unique)', max_length=200, unique=True)),
                ('code', models.CharField(help_text='System code (e.g., ERP, CRM, HRIS)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the system', null=True)),
                ('system_type', models.CharField(choices=[('Web Application', 'Web Application'), ('Desktop Application', 'Desktop Application'), ('Mobile Application', 'Mobile Application'), ('Database', 'Database'), ('API', 'API'), ('Operating System', 'Operating System'), ('Network Device', 'Network Device'), ('Cloud Service', 'Cloud Service'), ('Third-party Service', 'Third-party Service'), ('Internal Tool', 'Internal Tool'), ('Legacy System', 'Legacy System'), ('Other', 'Other')], default='Web Application', help_text='The type of the system (e.g., Application, Database, Network Device).', max_length=50)),
                ('criticality_level', models.CharField(choices=[('Critical', 'Critical - Business Critical'), ('High', 'High - Important'), ('Medium', 'Medium - Standard'), ('Low', 'Low - Nice to Have')], default='Medium', help_text='Business criticality level', max_length=20)),
                ('environment_type', models.CharField(choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Testing', 'Testing'), ('Development', 'Development'), ('Training', 'Training'), ('DR', 'Disaster Recovery'), ('Sandbox', 'Sandbox')], default='Production', help_text='Environment type', max_length=20)),
                ('url', models.URLField(blank=True, help_text='System URL or endpoint', null=True, validators=[django.core.validators.URLValidator()])),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='System IP address (if applicable)', null=True)),
                ('server_name', models.CharField(blank=True, help_text='Server hostname or name', max_length=200, null=True)),
                ('version', models.CharField(blank=True, help_text='Current system version', max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, help_text='System vendor or provider', max_length=200, null=True)),
                ('vendor_contact', models.CharField(blank=True, help_text='Vendor contact information', max_length=200, null=True)),
                ('support_contact', models.CharField(blank=True, help_text='Internal support contact', max_length=200, null=True)),
                ('documentation_url', models.URLField(blank=True, help_text='Link to system documentation', null=True, validators=[django.core.validators.URLValidator()])),
                ('authentication_type', models.CharField(choices=[('Local', 'Local Authentication'), ('LDAP', 'LDAP/Active Directory'), ('SSO', 'Single Sign-On'), ('OAuth', 'OAuth'), ('SAML', 'SAML'), ('API Key', 'API Key'), ('Certificate', 'Certificate'), ('Multi-Factor', 'Multi-Factor Authentication'), ('External', 'External Authentication')], default='Local', help_text='Authentication method used', max_length=30)),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether access requires approval')),
                ('approval_workflow', models.TextField(blank=True, help_text='Description of approval workflow', null=True)),
                ('access_instructions', models.TextField(blank=True, help_text='Instructions for accessing the system', null=True)),
                ('password_policy', models.TextField(blank=True, help_text='Password requirements and policies', null=True)),
                ('session_timeout', models.IntegerField(blank=True, help_text='Session timeout in minutes (if applicable)', null=True)),
                ('data_classification', models.CharField(blank=True, help_text='Data classification level (e.g., Public, Internal, Confidential)', max_length=50, null=True)),
                ('compliance_requirements', models.TextField(blank=True, help_text='Compliance requirements (SOX, HIPAA, etc.)', null=True)),
                ('backup_frequency', models.CharField(blank=True, help_text='Backup frequency and schedule', max_length=50, null=True)),
                ('disaster_recovery_plan', models.TextField(blank=True, help_text='Disaster recovery procedures', null=True)),
                ('maintenance_window', models.CharField(blank=True, help_text='Scheduled maintenance window', max_length=200, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Last maintenance date', null=True)),
                ('next_maintenance_date', models.DateField(blank=True, help_text='Next scheduled maintenance', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this system is currently active')),
                ('is_monitored', models.BooleanField(default=True, help_text='Whether system is actively monitored')),
                ('sla_uptime_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='SLA uptime percentage (e.g., 99.95)', max_digits=5, null=True)),
                ('sla_response_time_hours', models.IntegerField(blank=True, help_text='SLA response time in hours', null=True)),
                ('sla_resolution_time_hours', models.IntegerField(blank=True, help_text='SLA resolution time in hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_created', to=settings.AUTH_USER_MODEL)),
                ('system_owner', models.ForeignKey(blank=True, help_text='System owner/business owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_systems', to=settings.AUTH_USER_MODEL)),
                ('technical_lead', models.ForeignKey(blank=True, help_text='Technical lead/administrator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_systems', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'ordering': ['name'],
            },
        ),
    ]
