# Generated by Django 5.2.8 on 2025-12-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_contact_name', models.CharField(blank=True, help_text='Support contact full name', max_length=200, null=True)),
                ('support_contact_role', models.CharField(blank=True, help_text='Support contact role/title', max_length=100, null=True)),
                ('support_contact_phone', models.CharField(blank=True, help_text='Support contact phone number', max_length=50, null=True)),
                ('support_contact_email', models.EmailField(blank=True, help_text='Support contact email', max_length=254, null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='Contract renewal date', null=True)),
                ('renewal_duration_value', models.PositiveIntegerField(default=1, help_text='Duration value (e.g., 1 year)')),
                ('renewal_duration_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='years', help_text='Duration unit (months/years)', max_length=10)),
                ('contract_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base contract fee amount', max_digits=12, null=True)),
                ('contract_fee_currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=10)),
                ('fee_type', models.CharField(choices=[('recurring', 'Recurring'), ('one_time', 'One-time'), ('hybrid', 'Hybrid / Mixed')], default='recurring', help_text='Recurring or one-time fee structure', max_length=10)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='yearly', help_text='Billing cadence for recurring fees', max_length=10)),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms (e.g., Net 30, milestones)', max_length=200, null=True)),
                ('vat_included', models.BooleanField(default=False, help_text='Whether VAT is included in the fee amount')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='VAT percentage (e.g., 5 for 5%)', max_digits=5, null=True)),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Enable in-app reminders for renewal')),
                ('reminder_days_before', models.PositiveIntegerField(default=60, help_text='Days before renewal to flag reminders')),
                ('renewal_copy', models.FileField(blank=True, help_text='Upload renewal or contract copy', null=True, upload_to='system_contracts/renewal_copies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='systems.system')),
            ],
            options={
                'verbose_name': 'System Contract',
                'verbose_name_plural': 'System Contracts',
                'ordering': ['renewal_date'],
            },
        ),
    ]

