# Generated by Django 5.2.8 on 2025-12-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_systemcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontract',
            name='exchange_rate_to_local',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rate to convert billing currency to local (local = billing * rate)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='systemcontract',
            name='local_currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('SAR', 'SAR - Saudi Riyal'), ('AED', 'AED - UAE Dirham'), ('KWD', 'Kuwaiti Dinar'), ('QAR', 'Qatari Riyal'), ('OMR', 'Omani Rial'), ('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default='USD', help_text='Local/home currency for reporting', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemcontract',
            name='contract_fee_currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('SAR', 'SAR - Saudi Riyal'), ('AED', 'AED - UAE Dirham'), ('KWD', 'Kuwaiti Dinar'), ('QAR', 'Qatari Riyal'), ('OMR', 'Omani Rial'), ('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default='USD', help_text='Billing currency', max_length=10),
        ),
    ]

