# Generated by Django 5.2.8 on 2025-12-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_systemcontract_currency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcontract',
            name='contract_fee_currency',
            field=models.CharField(default='USD', help_text='Billing currency (ISO code, e.g., USD, EUR)', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemcontract',
            name='local_currency',
            field=models.CharField(default='USD', help_text='Local/home currency for reporting (ISO code)', max_length=10),
        ),
    ]


