# Generated by Django 5.2.8 on 2025-12-10 00:05

from django.db import migrations, models

import systems.models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_systemcontract_currency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcontract',
            name='contract_fee_currency',
            field=models.CharField(choices=systems.models.SystemContract.CURRENCY_CHOICES, default='USD', help_text='Billing currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemcontract',
            name='local_currency',
            field=models.CharField(choices=systems.models.SystemContract.CURRENCY_CHOICES, default='USD', help_text='Local/home currency for reporting', max_length=10),
        ),
    ]


