# Generated by Django 5.2.8 on 2025-12-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_add_currency_choices_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontract',
            name='due_amount_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Explicit monthly due amount (billing currency)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemcontract',
            name='due_amount_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Explicit yearly due amount (billing currency)', max_digits=12, null=True),
        ),
    ]



