# Generated by Django 5.2.8 on 2025-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_systemcontract_due_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('Web Application', 'Web Application'), ('Desktop Application', 'Desktop Application'), ('Mobile Application', 'Mobile Application'), ('Database', 'Database'), ('API', 'API'), ('Operating System', 'Operating System'), ('Network Device', 'Network Device'), ('Cloud Service', 'Cloud Service'), ('Third-party Service', 'Third-party Service'), ('Internal Tool', 'Internal Tool'), ('Legacy System', 'Legacy System'), ('Email Subscription', 'Email Subscription'), ('Other', 'Other')], default='Web Application', help_text='The type of the system (e.g., Application, Database, Network Device).', max_length=50),
        ),
    ]



