# Generated by Django 5.2.8 on 2025-12-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_add_email_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='License or SKU name (e.g., E1, E3)', max_length=100)),
                ('license_category', models.CharField(blank=True, help_text='Category key to match assigned users (e.g., E1, E3)', max_length=100, null=True)),
                ('billing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price per seat in billing currency', max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for this tier', max_digits=5)),
                ('seats_committed', models.PositiveIntegerField(default=0, help_text='Contracted seats')),
                ('seats_manual', models.PositiveIntegerField(blank=True, help_text='Optional manual seats used override', null=True)),
                ('overage_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Overage price per extra seat (billing currency). Defaults to unit price if blank.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_tiers', to='systems.systemcontract')),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
            },
        ),
    ]

