# Generated by Django 5.2.8 on 2025-12-14 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_systemsubscriptiontier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base contract fee amount at time of snapshot', max_digits=12, null=True)),
                ('contract_fee_currency', models.CharField(blank=True, help_text='Billing currency at time of snapshot', max_length=10, null=True)),
                ('local_currency', models.CharField(blank=True, help_text='Local currency at time of snapshot', max_length=10, null=True)),
                ('exchange_rate_to_local', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate at time of snapshot', max_digits=18, null=True)),
                ('due_amount_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly due amount at time of snapshot', max_digits=12, null=True)),
                ('due_amount_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Yearly due amount at time of snapshot', max_digits=12, null=True)),
                ('payment_frequency', models.CharField(blank=True, help_text='Payment frequency at time of snapshot', max_length=10, null=True)),
                ('vat_included', models.BooleanField(default=False, help_text='Whether VAT was included at time of snapshot')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='VAT rate at time of snapshot', max_digits=5, null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='Renewal date at time of snapshot', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, help_text='Optional reason for the change', max_length=500, null=True)),
                ('contract', models.ForeignKey(help_text='The contract this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='systems.systemcontract')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract History',
                'verbose_name_plural': 'Contract Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', '-created_at'], name='systems_sys_contrac_872f19_idx'), models.Index(fields=['created_at'], name='systems_sys_created_0b614a_idx')],
            },
        ),
    ]
