# Generated by Django 5.2.8 on 2026-02-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_systemcontracthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='is_user_login_system',
            field=models.BooleanField(default=False, help_text='Mark if this system is a user login platform (e.g., Windows/Active Directory, LDAP). When enabled, the Administrator Access section (4.3) will be required for access assignments.'),
        ),
    ]
